# -*- coding: utf-8 -*-
"""Build the programme website from data/*.json.

Usage:
    python tools/build.py                 # validate, write site/data.js and dist/<single-file>.html
    python tools/build.py --check         # validate only, write nothing
    python tools/build.py --data data/    # read a different data folder

Exit code 1 on validation errors (nothing is written), 0 otherwise. Warnings never block.
"""
from __future__ import annotations

import argparse
import base64
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import DATA_DIR, DIST_DIR, SITE_DIR, stamp_site_cache, utf8_stdout  # noqa: E402
from dataio import load_data  # noqa: E402
from schedule import assemble  # noqa: E402
from validate import validate_dir  # noqa: E402

utf8_stdout()

SINGLE_FILE_NAME = "nucleus2026-programme.html"


def write_data_js(model: dict, site_dir: Path | None = None) -> Path:
    site = site_dir or SITE_DIR
    site.mkdir(parents=True, exist_ok=True)
    path = site / "data.js"
    payload = json.dumps(model, ensure_ascii=False, separators=(",", ":"))
    # keep </script> from ever terminating the inline script in the single-file build
    payload = payload.replace("</", "<\\/")
    path.write_text(
        "// Generated by tools/build.py — do not edit by hand.\n"
        f"window.PROGRAMME = {payload};\n",
        encoding="utf-8",
    )
    return path


def write_single_file(site_dir: Path | None = None, dist_dir: Path | None = None) -> Path | None:
    site = site_dir or SITE_DIR
    index = site / "index.html"
    if not index.exists():
        print("ПРЕДУПРЕЖДЕНИЕ: site/index.html пока нет — единый HTML-файл не собран")
        return None
    html = index.read_text(encoding="utf-8")

    def inline_css(match: re.Match) -> str:
        href = match.group(1).split("?", 1)[0]
        css_path = site / href
        if not css_path.exists():
            return match.group(0)
        css = css_path.read_text(encoding="utf-8")

        def font_to_data_uri(font_match: re.Match) -> str:
            rel = font_match.group(1).strip("'\"")
            fpath = (css_path.parent / rel).resolve()
            if not fpath.exists():
                return font_match.group(0)
            mime = "font/woff2" if fpath.suffix == ".woff2" else "font/woff"
            b64 = base64.b64encode(fpath.read_bytes()).decode("ascii")
            return f"url(data:{mime};base64,{b64})"

        css = re.sub(r"url\(([^)]+\.woff2?)\)", font_to_data_uri, css)
        return f"<style>\n{css}\n</style>"

    def inline_js(match: re.Match) -> str:
        src = match.group(1).split("?", 1)[0]
        js_path = site / src
        if not js_path.exists():
            return match.group(0)
        js = js_path.read_text(encoding="utf-8").replace("</script", "<\\/script")
        return f"<script>\n{js}\n</script>"

    html = re.sub(r'<link\s+rel="stylesheet"\s+href="([^"]+)"\s*/?>', inline_css, html)
    html = re.sub(r'<script\s+src="([^"]+)"\s*></script>', inline_js, html)
    html = re.sub(r'\s*<link\s+rel="manifest"[^>]*>', "", html)
    html = re.sub(r'\s*<link\s+rel="apple-touch-icon"[^>]*>', "", html)
    html = re.sub(r'\s*<link\s+rel="icon"[^>]*>', "", html)

    dist = dist_dir or DIST_DIR
    dist.mkdir(parents=True, exist_ok=True)
    out = dist / SINGLE_FILE_NAME
    out.write_text(html, encoding="utf-8")
    return out


def build_programme(data_dir: Path, *, generated_at: str | None = None) -> dict:
    return assemble(load_data(data_dir), generated_at=generated_at)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Build site/data.js from data/*.json.")
    parser.add_argument("--data", type=Path, default=None)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--site", type=Path, default=SITE_DIR)
    args = parser.parse_args(argv)
    data_dir = args.data or DATA_DIR
    diag = validate_dir(data_dir)
    for msg in diag.warnings:
        print(f"ПРЕДУПРЕЖДЕНИЕ: {msg}")
    for msg in diag.errors:
        print(f"ОШИБКА: {msg}")
    if diag.errors:
        print(f"\nСборка остановлена: {len(diag.errors)} ошибок(и), {len(diag.warnings)} предупреждений.")
        return 1
    if args.check:
        print(f"\nПроверка пройдена ({len(diag.warnings)} предупреждений).")
        return 0
    model = build_programme(data_dir)
    data_path = write_data_js(model, args.site)
    print(f"\nЗаписано: {data_path}")
    single = write_single_file(args.site, DIST_DIR if args.site == SITE_DIR else args.site / "dist")
    if single:
        size_kb = single.stat().st_size / 1024
        print(f"Записано: {single} ({size_kb:.0f} КБ)")
    if args.site == SITE_DIR:
        tags = stamp_site_cache()
        if tags:
            print("Кэш: " + ", ".join(f"{k}={v}" for k, v in tags.items()))
    print(f"Готово. Предупреждений: {len(diag.warnings)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
